// frontend/src/app/notes/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {}

<nav class="navbar">
  <div class="logo">My Notes</div>
  <div class="nav-links">
    <a routerLink="/notes" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">All Notes</a>
    <a routerLink="/create" routerLinkActive="active">Create Note</a>
  </div>
</nav>

// frontend-react/src/components/navbar/Navbar.tsx
import { Link, useLocation } from "react-router-dom";
import "./Navbar.css";

function Navbar() {
  const location = useLocation();

  return (
    <nav className="navbar">
      <div className="navbar-logo">
        <i className="fas fa-sticky-note"></i> NotesApp
      </div>
      <ul className="navbar-links">
        <li className={location.pathname === "/" ? "active" : ""}>
          <Link to="/">Create Note</Link>
        </li>
        <li className={location.pathname === "/all-notes" ? "active" : ""}>
          <Link to="/all-notes">All Notes</Link>
        </li>
      </ul>
    </nav>
  );
}

export default Navbar;
